### ISSUE TITLE
Cannot find module 'discord-rich-presence'

### ISSUE THREAD

**Issue by SkylZone** [LoganMD/Crunchycord#5]
I follow all the instructions but i can't get this to work, i checked the logs and this is what i get : 
`0|Crunchyc |     at Object.Module._extensions..js (module.js:646:10)
0|Crunchyc |     at Module.load (module.js:554:32)
0|Crunchyc |     at tryModuleLoad (module.js:497:12)
0|Crunchyc |     at Function.Module._load (module.js:489:3)
0|Crunchyc | Error: Cannot find module 'discord-rich-presence'
0|Crunchyc |     at Function.Module._resolveFilename (module.js:536:15)
0|Crunchyc |     at Function.Module._load (module.js:466:25)
0|Crunchyc |     at Module.require (module.js:579:17)
0|Crunchyc |     at require (internal/module.js:11:18)
0|Crunchyc |     at Object.<anonymous> (C:\Users\Fabien\Desktop\Crunchycord-master\server\server.js:2:16)
0|Crunchyc |     at Module._compile (module.js:635:30)
0|Crunchyc |     at Object.Module._extensions..js (module.js:646:10)
0|Crunchyc |     at Module.load (module.js:554:32)
0|Crunchyc |     at tryModuleLoad (module.js:497:12)
0|Crunchyc |     at Function.Module._load (module.js:489:3)

C:\Users\Fabien\.pm2\logs\Crunchycord-out.log last 15 lines:
0|Crunchyc | Server is listening on 3000
0|Crunchyc | Server is listening on 3000
`
I have installed discord-rich-presence though. The node modules was empty by the way so i tried to installed it by myself in the directory but i can't get this to work sadly.

**Comment by LoganMD** [comment]
is that all the errors?

**Comment by SkylZone** [comment]
It kinda repeats the same thing but you can check it there : https://pastebin.com/1R9yEp74

**Comment by LoganMD** [comment]
try doing `npm init`, then install discord-rich-presence with `npm install discord-rich-presence --save`

**Comment by SkylZone** [comment]
I get the same thing : https://pastebin.com/cMiHAWj5

**Comment by LoganMD** [comment]
try installing it globally with `npm install discord-rich-presence -g`

**Comment by SkylZone** [comment]
it still doesn't works i'm searching on internet how to resolve problems like "cannot find modules" with nodejs

**Comment by LoganMD** [comment]
i dont know what the problem is then

**Comment by McStuffins** [comment]
@SkylZone You have to run `npm i` in the project directory or higher in the hierarchy. This is because node tries to resolve modules recursively up the tree starting at the file.

**Comment by SkylZone** [comment]
solve it for me, ty
